#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 31 10:50:00 2021

@author: joseph
"""

#your_name = input("Give me your name!!!!! ")
#prints index 6 until the end
#print(your_name[5:])

school = "Coral Gables Senior High"
#print out 10 letter
print(school[9])

"""
print out from the tenth letter 
to the end of the string

"""
print(school[9:])

#Print out the second to fifth letter
print(school[1:4])

#In reverse?
print(school[0::-1])

#the length of the string?
L = len(school)
print("Size of string is: ",L)
#print every other letter
print(school[0:L-1:2])

print("where is the space in String?")
print(school.index(" "))
print("Where is the second space in String?")
print(school.index(" ", 6))
print(school[:5])
print(school[6:12])

month = input("Birth month: ")
day = input("Birth day: ")
year = input("Birth year: ")
n = input("Your First and Last Name: ")

space = n.index(" ")
initials = n[0] + n[space + 1]
print("Your Gables Password is: ")
print(month + day + year + initials)
